// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace FrontEnd.Agents.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CursusInstantie
    {
        /// <summary>
        /// Initializes a new instance of the CursusInstantie class.
        /// </summary>
        public CursusInstantie() { }

        /// <summary>
        /// Initializes a new instance of the CursusInstantie class.
        /// </summary>
        public CursusInstantie(Cursus cursus, string startdatum, int? id = default(int?))
        {
            Id = id;
            Cursus = cursus;
            Startdatum = startdatum;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursus")]
        public Cursus Cursus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startdatum")]
        public string Startdatum { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Cursus == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Cursus");
            }
            if (Startdatum == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Startdatum");
            }
            if (this.Cursus != null)
            {
                this.Cursus.Validate();
            }
            if (this.Startdatum != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(this.Startdatum, "^[1-3]?[0-9]/1?[0-9]/\\d{4}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Startdatum", "^[1-3]?[0-9]/1?[0-9]/\\d{4}$");
                }
            }
        }
    }
}
